appname = todo-api
httpport = 8080
runmode = dev
# exmaple frontendurl = http://localhost:5173
frontendurl = frontend_url

[database]
DB_HOST = db_host
DB_PORT = db_port
DB_USER = db_username
DB_PASSWORD = db_password
DB_NAME = db_name

[secret]
JWT_SECRET = jwt_secret_key