appname = todo-api
httpport = 8080
runmode = dev

[database]
DB_HOST = <hostname>
DB_PORT = XXXX
DB_USER = exampleuser
DB_PASSWORD = examplepassword
DB_NAME = exampledb

[jwt]
JWT_SECRET = your_jwt_secret_key_here